version: '3.1'

services:
  php:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 8099:80
    volumes:
      - .:/var/www/html/

  db:
    image: mysql
    ports:
      - "3666:3306"
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: example

volumes:
    mysql-data: